/*
* generated by Xtext
*/
package org.eclipse.ocl.tutorial.eclipsecon2011.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class OCLStatesOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
