/*
* generated by Xtext
*/
package org.eclipse.ocl.tutorial.eclipsecon2011.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.eclipse.ocl.tutorial.eclipsecon2011.services.OCLStatesGrammarAccess;

public class OCLStatesParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private OCLStatesGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.eclipse.ocl.tutorial.eclipsecon2011.parser.antlr.internal.InternalOCLStatesParser createParser(XtextTokenStream stream) {
		return new org.eclipse.ocl.tutorial.eclipsecon2011.parser.antlr.internal.InternalOCLStatesParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Module";
	}
	
	public OCLStatesGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(OCLStatesGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
