/*
 * generated by Xtext
 */
package org.eclipse.ocl.tutorial.eclipsecon2011.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class OCLStatesUiModule extends org.eclipse.ocl.tutorial.eclipsecon2011.ui.AbstractOCLStatesUiModule {
	public OCLStatesUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
