/*
* generated by Xtext
*/
package org.eclipse.ocl.tutorial.eclipsecon2011.ui.contentassist;

import org.eclipse.ocl.tutorial.eclipsecon2011.ui.contentassist.AbstractOCLStatesProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class OCLStatesProposalProvider extends AbstractOCLStatesProposalProvider {

}
