<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="hosp" nsURI="hosp" nsPrefix="hosp">
  <eClassifiers xsi:type="ecore:EClass" name="Hospital">
    <eOperations name="admitPatient">
      <eParameters name="p" lowerBound="1" eType="#//Patient"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="patients" lowerBound="1"
        upperBound="-1" eType="#//Patient" eOpposite="#//Patient/hospital"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="beds" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Patient">
    <eStructuralFeatures xsi:type="ecore:EReference" name="hospital" lowerBound="1"
        eType="#//Hospital" eOpposite="#//Hospital/patients"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
</ecore:EPackage>
